### ISSUE TITLE
Hue Error Following Update on Hubitat

### ISSUE THREAD

**Issue by budjik-tech** [apwelsh/hubitat#26]
Unexpected Error
An unexpected error has occurred trying to load the app. Check Logs for more information.

Error: No signature of method: user_app_apwelsh_Advanced_Hue_Bridge_Integration_172.unsubscrive() is applicable for argument types: () values: [] Possible solutions: subscribe(), subscribe(java.lang.Object, java.lang.String, groovy.lang.MetaMethod), subscribe(java.lang.Object, java.lang.String, java.lang.String), subscribe(java.lang.Object, java.lang.String, groovy.lang.MetaMethod, java.util.Map), subscribe(java.lang.Object, java.lang.String, java.lang.String, java.util.Map)

**Comment by apwelsh** [comment]
Oops. Fixing.

**Comment by apwelsh** [comment]
Fixed

**Comment by budjik-tech** [comment]
Confirm update has fixed error.
Thank you for the speedy fix.
